#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port7,           Hook,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           openclose,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           touchclaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
void pre_auton()
{
	bStopTasksBetweenModes = true;
}
//do not mess with anthing above this!


//****************************************autonomus****************************************
void doAutonomous()
{
	if(vexRT[Btn7R])
	{
		motor[right] = 127;
		motor[left] = 127;
		wait1Msec(3000);


}

task autonomous()
{
	doAutonomous();
}

//****************************************usercontrol***************************************
task usercontrol()
{
	while (true)
	{
		if(vexRT[Btn7L] == 1)
		{
			doAutonomous();
		}


		//joystick controls for driving
		motor[right] = vexRT[Ch2];
		motor[left] = vexRT[Ch3];

		//Buttons to move arm
		if(vexRT[Btn5UXmtr2])
		{
			motor[touchclaw] = 120;
		}
		else if(vexRT[Btn5DXmtr2])
		{
			motor[touchclaw] = -80;
		}
		else
		{
			motor[touchclaw] = 0;
		}

		//Buttons to open / close claw
		if(vexRT[Btn6UXmtr2])
		{
			motor[openclose] = 127;
		}
		else if(vexRT[Btn6DXmtr2])
		{
			motor[openclose] = -127;
		}
		else
		{
			motor[openclose] = 0;
			//Buttons to hook for hang hook
			if(vexRT[Btn7UXmtr2])
			{
				motor[Hook] = 127;
			}
			  wait1Msec(1000);
			{
				motor[Hook] = 0;
		  }
		}
	}
}
	//fun code of the day "log.output("hi");" what will this code do and what langwedge
